### ISSUE TITLE
I can't understand how this works.

### ISSUE THREAD

**Issue by splashbxcv** [JasonEl1/DLS-Player-Search#1]

**Comment by JasonEl1** [comment]
@SplashBoom Sorry to hear that it isn't too intuitive for you, maybe I need to add some instructions for it. Open the github.io link and search for either a last name, first name, or both. Click on the search button or use your enter key and the site will find players matching your search terms in a database of DLS players. This is still very much a work-in-progress so the results aren't fully finished yet, you should get the name of the player, their photo, and their position.

**Comment by JasonEl1** [comment]
@SplashBoom I've added instructions in README.md, which hopefully will help you understand how to use this.
